Repository universal-ctags/ctags, pull requests merged in 2022-01, with the labels that each got.

#3256 buildsys,mingw: Fix link error with PCRE2
  configure.ac
Labels: Windows

#3257 packaging,win32: Add PCRE2's LICENCE file
  win32/license/LICENCE.pcre2
Labels: Packaging, Windows

#3259 packaging,win32: Install autotools
  win32/appveyor.bat
Labels: Packaging, Windows

#3260 build-sys: Don't use weak symbols on MSYS2
  configure.ac
Labels: BUILDSYS|git operation|workflow|test harness, Windows

#3229 Cxx: accept bit-width for enum-typed structure member
  Units/parser-c.r/enum-bit-fields.d/args.ctags
  Units/parser-c.r/enum-bit-fields.d/expected.tags
  Units/parser-c.r/enum-bit-fields.d/input.c
  parsers/cxx/cxx_parser.c
Labels: C/C++
